apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-deployment
  template:
    metadata:
      labels:
        app: spring-boot-deployment
    spec:
      containers:
      - name: spring-boot-deployment
        image: nobleson/robotapocalypse:latest
        ports:
        - containerPort: 8080